//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::customers::Entity as Customers;
pub use super::invoices::Entity as Invoices;
pub use super::notes::Entity as Notes;
pub use super::revenues::Entity as Revenues;
pub use super::users::Entity as Users;
